const CONSTS = {
  ADD_TODO: 'ADD_TODO',
  ADD_TODO_SUCCESS: 'ADD_TODO_SUCCESS',
  ADD_TODO_FAIL: 'ADD_TODO_FAIL',

  EDIT_TODO: 'EDIT_TODO',
  EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
  EDIT_TODO_FAIL: 'EDIT_TODO_FAIL',

  DELETE_TODO: 'DELETE_TODO',
  DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
  DELETE_TODO_FAIL: 'DELETE_TODO_FAIL',

  // asyncStorage
  AS_TODOS: 'AS_TODOS',
};

export default CONSTS;
